In [2]:
import pandas as pd

In [3]:
import numpy as np

In [8]:
pd.__version__


'2.3.1'

pd.__version__


In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv


--2025-09-25 09:41:40--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  3.59MB/s    in 0.2s    

2025-09-25 09:41:40 (3.59 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [4]:
df= pd.read_csv('car_fuel_efficiency.csv')

# Q2. Records count


In [19]:
len(df)

9704

In [20]:
# Q3. Fuel types How many fuel types are presented in the dataset? --2

In [21]:
df['fuel_type'].describe()

count         9704
unique           2
top       Gasoline
freq          4898
Name: fuel_type, dtype: object

In [22]:
# Q4. Missing values How many columns in the dataset have missing values? --4

In [9]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [24]:
# What's the maximum fuel efficiency of cars from Asia? --23.759122836520497


In [25]:
df[df.origin.str.lower() == 'asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

Q6. Median value of horsepower
Find the median value of horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No

In [ ]:
# Q6. Median value of horsepower --149.0)
df['horsepower'].median() #149.0

mfv = df['horsepower'].mode()[0] # 152.0
#Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
df['horsepower']=df['horsepower'].fillna(mfv)


# Now, calculate the median value of horsepower once again.
df['horsepower'].median() # np.float64(152.0)

# It has increased


np.float64(152.0)

7. Sum of weights
Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

In [ ]:
df_fil.tra

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [48]:
X_df = df_fil.iloc[:7]

# Step 4: Get the underlying NumPy array
X = X_df.to_numpy()

In [49]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [51]:
X = df_fil[:7].values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [5]:
#Select all the cars from Asia
df_asia = df[df['origin'].str.lower()=='asia']


#Select only columns vehicle_weight and model_year
df_fil = df_asia[['vehicle_weight','model_year']]


#Select the first 7 values
df_fil[:7]

#Get the underlying NumPy array. Let's call it X.
X = df_fil[:7].values

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
xt = X.transpose()
XTX = xt.dot(X)

#Invert XTX.
XTX_inv = np.linalg.inv(XTX)


#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array( [1100, 1300, 800, 900, 1000, 1100, 1200])
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
res=XTX_inv.dot(xt)
final = res.dot(y)
#What's the sum of all the elements of the result?

In [7]:
final.sum()

np.float64(0.5187709081074016)

In [55]:
xt = X.transpose()
XTX = xt.dot(X)
XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])